apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: k8shpatest-custom
  namespace: k8shpatest
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8shpatest
  metrics:
    - type: Pods
      pods:
        metric: 
          name: fs_writes
        target:
          type: AverageValue
          averageValue: "1000m"        
