apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8shpatest
  namespace: k8shpatest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8shpatest
  template:
    metadata:
      labels:
        app: k8shpatest
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: k8shpatest
        image: zesow/k8shpatest:v8
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: k8shpatest
  namespace: k8shpatest
spec:
  type: NodePort
  selector:
    app: k8shpatest
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
